// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhuark6GkRpLjY95XVf4dlcrXxgnCUF2M',
    appId: '1:695942377318:web:092f5ce63875ea133722a7',
    messagingSenderId: '695942377318',
    projectId: 'do-eat-app',
    authDomain: 'do-eat-app.firebaseapp.com',
    storageBucket: 'do-eat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEcHxR9EYdsXVj4_HLM2Z6nG6ctm27deg',
    appId: '1:695942377318:android:b443de28c00185643722a7',
    messagingSenderId: '695942377318',
    projectId: 'do-eat-app',
    storageBucket: 'do-eat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEnZ8jjes3o3VhE2tuDjoWgTj-Q1YI94',
    appId: '1:695942377318:ios:7a9381021a8c8fb63722a7',
    messagingSenderId: '695942377318',
    projectId: 'do-eat-app',
    storageBucket: 'do-eat-app.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEnZ8jjes3o3VhE2tuDjoWgTj-Q1YI94',
    appId: '1:695942377318:ios:7a9381021a8c8fb63722a7',
    messagingSenderId: '695942377318',
    projectId: 'do-eat-app',
    storageBucket: 'do-eat-app.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhuark6GkRpLjY95XVf4dlcrXxgnCUF2M',
    appId: '1:695942377318:web:b377a3a472d27a783722a7',
    messagingSenderId: '695942377318',
    projectId: 'do-eat-app',
    authDomain: 'do-eat-app.firebaseapp.com',
    storageBucket: 'do-eat-app.appspot.com',
  );
}
